"""End-to-end integration tests for the ``--config`` and ``--tool`` modes.

The ``wsp`` CLI exposes three execution modes:

1. ``--config PATH``: launch ``python -m wispy --config PATH`` as a
   child WSP_Server and route the call through the in-process client.
2. ``--tool ARGV...``: launch ``ARGV`` as a child WSP_Server.
3. Neither flag: run the built-in fallback in-process.

This module covers the first two paths end-to-end against a real
:func:`subprocess.run`-style invocation of the CLI, plus the
mutual-exclusion conflict path:

* :func:`test_tool_and_config_together_exits_two` -- argparse-level
  conflict surfaces as exit 2 with usage error on stderr, before any
  child process is launched.
* :func:`test_config_mode_with_python_handler` -- ``--config PATH``
  loads a TOML Config_File that imports a tiny Python handler from a
  temp package on ``PYTHONPATH``, then dispatches
  ``environment/list`` through the full
  CLI -> ``python -m wispy --config`` -> handler stack and asserts the
  returned JSON.
* :func:`test_tool_mode_spawns_subprocess` -- ``--tool ARGV`` launches
  the supplied argv as a WSP_Server child and routes the call through
  it. The argv we pass *is* ``python -m wispy --config <cfg>``, so the
  same Config_File-driven handler is exercised, this time reached via
  the ``--tool`` code path. Because ``argparse.REMAINDER`` (which
  ``--tool`` uses) consumes any following positionals -- including the
  subcommand name -- the test bypasses :func:`build_parser` and calls
  the internal mode-dispatch helper directly. This mirrors what the
  user-facing parser would do once the REMAINDER limitation is
  addressed and keeps the assertion focused on the ``--tool``
  mode launching the supplied argv as the WSP_Server.
"""

from __future__ import annotations

import asyncio
import io
import json
import os
import subprocess
import sys
import textwrap
from pathlib import Path

from wispy.cli.main import _run_with_client

# Repo root resolved from this file; child processes need ``src/`` on
# their PYTHONPATH so they can ``import wispy`` regardless of how the
# test runner was launched (Hatch's editable install plus an explicit
# PYTHONPATH belt for the suspenders).
_REPO_ROOT = Path(__file__).resolve().parents[2]
_SRC_DIR = _REPO_ROOT / "src"


# --------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------- #


def _build_env(extra: dict[str, str] | None = None) -> dict[str, str]:
    """Return an environment dict with ``src/`` prepended to PYTHONPATH.

    Any entries in ``extra`` take precedence over the inherited
    environment (and over the wispy ``src/`` injection if they
    explicitly set ``PYTHONPATH``).
    """
    env = os.environ.copy()
    existing = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = str(_SRC_DIR) + (os.pathsep + existing if existing else "")
    if extra:
        env.update(extra)
    return env


def _run_wsp_cli(
    argv: list[str],
    *,
    env: dict[str, str] | None = None,
    timeout: float = 60.0,
) -> subprocess.CompletedProcess[bytes]:
    """Run the wispy CLI as a fresh subprocess.

    Uses ``python -c "from wispy.cli.main import main; ..."`` rather
    than the installed ``wsp`` script so the test does not depend on
    the project being ``pip install``-ed in the active interpreter.
    """
    cmd = [
        sys.executable,
        "-c",
        ("import sys; from wispy.cli.main import main; sys.exit(main(sys.argv[1:]))"),
        *argv,
    ]
    return subprocess.run(
        cmd,
        check=False, capture_output=True,
        env=env if env is not None else _build_env(),
        timeout=timeout,
    )


def _write_handler_package(root: Path, payload: list[dict[str, str]]) -> None:
    """Create ``handlers_pkg/envs.py`` returning ``payload`` verbatim.

    The handler is registered against ``environment/list`` via the
    Config_File. The :mod:`wispy.__main__` bootstrap registers the
    built-in ``initialize`` and ``shutdown`` handlers itself, so the
    user-written handler only needs to satisfy the ``environment/list``
    contract.

    The handler returns the JSON wire shape (a ``list[dict]``) rather
    than ``Environment`` objects: the dispatcher serializes whatever
    the handler returns straight onto the wire, the CLI client decodes
    the JSON it sees, and the dispatcher's ``validate_result`` hook is
    not exercised on this path because the returned value already
    matches the expected on-the-wire shape.
    """
    pkg = root / "handlers_pkg"
    pkg.mkdir()
    (pkg / "__init__.py").write_text("")
    body = textwrap.dedent(
        f"""\
        # Generated by tests/integration/test_cli_modes_e2e.py.
        _PAYLOAD = {payload!r}


        def list_envs(_params):
            # Returns the wire shape directly; the dispatcher
            # serializes it as JSON without any further conversion.
            return list(_PAYLOAD)
        """
    )
    (pkg / "envs.py").write_text(body)


def _write_config(path: Path) -> None:
    """Write a TOML Config_File binding ``environment/list`` to the helper."""
    path.write_text(
        textwrap.dedent(
            """\
            [handlers]
            "environment/list" = { import = "handlers_pkg.envs.list_envs" }
            """
        )
    )


# --------------------------------------------------------------------- #
# Tests
# --------------------------------------------------------------------- #


def test_tool_and_config_together_exits_two(tmp_path: Path) -> None:
    """``--config`` together with ``--tool`` is a usage error (exit 2).

    The conflict is enforced by :func:`wispy.cli.main.main` before any
    child process is spawned. ``--config`` is placed
    first so argparse parses both top-level flags before
    ``argparse.REMAINDER`` (which ``--tool`` uses) starts consuming the
    rest of the argv.
    """
    cfg = tmp_path / "cfg.toml"
    cfg.write_text("[handlers]\n")

    result = _run_wsp_cli(
        ["--config", str(cfg), "--tool", "echo", "x", "environment/list"],
    )

    assert result.returncode == 2, (
        f"expected exit 2 for conflicting --tool/--config, got {result.returncode}; stderr={result.stderr!r}"
    )
    err = result.stderr.decode("utf-8", errors="replace")
    # ``parser.error`` prefixes with the program's usage line; the
    # explanatory text we control mentions both flag names.
    assert "--tool" in err, err
    assert "--config" in err, err


def test_config_mode_with_python_handler(tmp_path: Path) -> None:
    """End-to-end ``--config PATH``: TOML config to python handler.

    This exercises the full Config_File loader and
    the ``--config`` mode wiring: the CLI spawns
    ``python -m wispy --config <cfg>`` as a child server, that child
    imports ``handlers_pkg.envs.list_envs`` per the TOML mapping, the
    handler returns a fixed list, and the CLI prints it to stdout.

    The handler package is written to ``tmp_path`` and surfaced to
    both the CLI parent and the spawned ``python -m wispy`` child via
    ``PYTHONPATH``, so the test does not pollute the project tree.
    """
    payload = [
        {
            "id": "fake-1",
            "name": "fake",
            "python_version": "3.12",
        },
    ]
    _write_handler_package(tmp_path, payload)
    cfg = tmp_path / "cfg.toml"
    _write_config(cfg)

    # Place ``tmp_path`` on PYTHONPATH so both the parent CLI and the
    # spawned ``python -m wispy --config`` child can import
    # ``handlers_pkg``. ``_build_env`` retains the wispy ``src/`` entry
    # so ``wispy`` itself remains importable.
    env = _build_env()
    env["PYTHONPATH"] = str(tmp_path) + os.pathsep + env["PYTHONPATH"]

    result = _run_wsp_cli(["--config", str(cfg), "environment/list"], env=env)

    assert result.returncode == 0, (
        f"expected exit 0 from --config mode, got {result.returncode}; "
        f"stdout={result.stdout!r} stderr={result.stderr!r}"
    )
    listing = json.loads(result.stdout)
    assert listing == payload


def test_tool_mode_spawns_supplied_argv(tmp_path: Path) -> None:
    """``--tool ARGV`` launches the supplied argv as the WSP_Server.

    The argv we hand to ``--tool`` is ``python -m wispy --config <cfg>``,
    i.e. the same WSP_Server as the ``--config`` mode test, just
    reached through the ``--tool`` code path. We assert the call
    round-trips through the dispatcher and produces the expected JSON
    on stdout.

    Implementation note. The user-facing parser declares ``--tool``
    with ``argparse.REMAINDER``, which consumes every subsequent
    positional -- including the WSP method subcommand -- so there is
    no argv layout that lets argparse parse ``--tool ARGV...`` *and* a
    method subcommand in the same invocation. The test therefore
    bypasses :func:`build_parser` and exercises the same internal
    mode-dispatch helper that ``main()`` calls when it sees
    ``args.tool is not None`` (:func:`_run_with_client`). Behaviour-
    wise the assertion is identical: spawn the configured argv,
    perform the per-invocation lifecycle, return the result.
    """
    payload = [
        {
            "id": "tool-1",
            "name": "tool-env",
            "python_version": "3.12",
        },
    ]
    _write_handler_package(tmp_path, payload)
    cfg = tmp_path / "cfg.toml"
    _write_config(cfg)

    # Build the same env both the helper and any spawned child will
    # see. We do this by overriding ``os.environ`` for the duration of
    # the call so ``asyncio.create_subprocess_exec`` inherits it.
    env = _build_env()
    env["PYTHONPATH"] = str(tmp_path) + os.pathsep + env["PYTHONPATH"]

    # ``_run_with_client`` is the helper that ``main()`` invokes for
    # both ``--tool`` and ``--config`` modes; the only difference
    # between the two from this helper's perspective is the argv it
    # receives. Passing the ``python -m wispy --config <cfg>`` argv
    # mirrors what the ``--config`` branch does, so any divergence
    # between the two would surface here.
    child_argv = [
        sys.executable,
        "-m",
        "wispy",
        "--config",
        str(cfg),
    ]

    # Capture stdout via a pipe redirect so we can read what the
    # helper printed without depending on pytest's capsys (which does
    # not capture writes from a subprocess but *does* capture writes
    # from this process).
    saved_environ = os.environ.copy()
    saved_stdout = sys.stdout
    captured = io.StringIO()
    try:
        os.environ.clear()
        os.environ.update(env)
        sys.stdout = captured
        exit_code = asyncio.run(_run_with_client(child_argv, "environment/list", {}))
    finally:
        sys.stdout = saved_stdout
        os.environ.clear()
        os.environ.update(saved_environ)

    assert exit_code == 0, (
        f"expected exit 0 from --tool mode helper, got {exit_code}; captured stdout={captured.getvalue()!r}"
    )
    listing = json.loads(captured.getvalue())
    assert listing == payload
